# this works, now the returned object has a user and the user will have the blog in the blogs array
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "another last blog post",
  "author": "bananenphil-4",
  "url": "https://websiteofwonders3.de",
  "likes": 15,
  "userId": "66964c313c399a7a0a37b7d6"
}
###
#does not work anymore because we need the userId
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "my third blog post",
  "author": "bananenphil",
  "url": "https://websiteofwonders2.de",
  "likes": 2
}